services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
      target: dev
    ports:
      - 1323:1323
    volumes:
      - ./app:/app
    init: true
    tty: true
    environment:
      TZ: Asia/Tokyo
    networks:
      - mixi_network
  db:
    image: mysql:8.3.0
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mixi
      TZ: Asia/Tokyo
    volumes:
      - db:/var/lib/mysql
      - ./app/db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mixi_network

networks:
  mixi_network:

volumes:
  db:
