services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 8090:8090
    volumes:
      - ./web/src:/web
      - ./web/nginx:/etc/nginx
    depends_on:
      - app
    init: true
    environment:
      TZ: Asia/Tokyo
    networks:
      - mixi_network
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
      target: dev
    ports:
      - 1323:1323
    volumes:
      - ./app:/app
    init: true
    tty: true
    environment:
      TZ: Asia/Tokyo
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mixi_network
  db:
    image: mysql:8.3.0
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mixi
      TZ: Asia/Tokyo
    volumes:
      - db:/var/lib/mysql
      - ./app/db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mixi_network
    healthcheck:
      test: "mysqladmin ping -h127.0.0.1 -uroot -ppassword "
      timeout: 5s
      interval: 5s
      retries: 5

networks:
  mixi_network:

volumes:
  db:
