services:
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - 8090:8090
    depends_on:
      - app
    init: true
    environment:
      TZ: Asia/Tokyo
    networks:
      - mixi_network
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/root/app
    ports:
      - 1323:1323
    init: true
    tty: true
    environment:
      TZ: Asia/Tokyo
    networks:
      - mixi_network

networks:
  mixi_network:
